export const PORTRAIT_LIST: string[] = [
  'basic.jpg',
  'chaos - beast.jpg',
  'chaos - beastmaster.jpg',
  'chaos - champion.jpg',
  'chaos - general.jpg',
  'chaos - marauder.jpg',
  'chaos - marauder-champion.jpg',
  'chaos - marauder-horn.jpg',
  'chaos - marauder-standard.jpg',
  'chaos - warrior-standard.jpg',
  'chaos - warrior.jpg',
  'dark angels - scout.jpg',
  'dark angels - sergeant.jpg',
  'dark angels - tactical marine.jpg',
  'enforcer-assault.jpg',
  'enforcer-commander.jpg',
  'enforcer-drone.jpg',
  'enforcer-engineer.jpg',
  'enforcer-flamethrower.jpg',
  'enforcer-heavymg.jpg',
  'enforcer-rifle.jpg',
  'enforcer-rocketlauncher.jpg',
  'enforcer-sniper.jpg',
  'necron-deathmark.jpg',
  'necron-flayedone.jpg',
  'necron-immortal.jpg',
  'necron-warrior.jpg',
  'plague-abomination.jpg',
  'plague-hound.jpg',
  'plague-troopermg.jpg',
  'plague-trooperpistol.jpg',
  'plague-trooperrifle.jpg',
  'plague-warrior.jpg',
  'skitarii-ranger-alpha.jpg',
  'skitarii-ranger-arquebus.jpg',
  'skitarii-ranger.jpg',
  'skitarii-vanguard-alpha.jpg',
  'skitarii-vanguard-arcrifle.jpg',
  'skitarii-vanguard-plasmacaliver.jpg',
  'skitarii-vanguard.jpg',
  'sylvaneth - branchwych.jpg',
  'sylvaneth - dryad.jpg',
  'sylvaneth - treelord.jpg',
  'templar - angel.jpg',
  'templar - general.jpg',
  'templar - knight.jpg',
  'templar - knight-captain.jpg',
  'templar - paladin.jpg',
  'templar - soulwarden.jpg'
];
