// load the generic node & express libraries
import * as express from 'express';
import * as path from 'path';
import * as bodyParser from 'body-parser';

// load the various application routers
import modelRouter from './routes/modelRouter';

// create the express application
var app = express();

// load up the generic pre-processing middleware 
app.use(bodyParser. json());
 
// load up routers for the static files, including those generated by angular
app.use(express.static( path.join(__dirname, 'static') ) );

// API routers
app.use('/api', modelRouter);

// start listening
app.listen(3000, function () {
    console.log('Example app listening on port 3000!');
});