// load the generic node & express libraries
import * as express from 'express';
import * as path from 'path';
import * as bodyParser from 'body-parser';

// load the various application routers
import modelRouter from './routers/modelRouter';

// create the express application
const app = express();

// load up the generic pre-processing middleware 
app.use(bodyParser. json());
 
// load up routers for the static files, including those generated by angular
app.use(express.static( path.join(__dirname, 'static') ) );

// API routers
app.use("/api", modelRouter);

// start listening, port is configured using environment variables
const PORT = process.env.PORT || 3000;
app.listen(PORT, function () {
    console.log("App listening on port " + PORT + "!");
});